version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - web

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pewpewlogs
    networks:
      - web
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.pewpewlogs_http.entrypoints=web"
      - "traefik.http.routers.pewpewlogs.service=pewpewlogs"
      - "traefik.http.routers.pewpewlogs_http.rule=Host(`${FQDN_PEWPEWLOGS}`)"
      - "traefik.http.routers.pewpewlogs_http.middlewares=redirect-web-to-websecure@internal"
      - "traefik.http.routers.pewpewlogs.rule=Host(`${FQDN_PEWPEWLOGS}`)"
      - "traefik.http.routers.pewpewlogs.entrypoints=websecure"
      - "traefik.http.routers.pewpewlogs.tls.certresolver=lets-encrypt"
      - "traefik.http.services.pewpewlogs.loadBalancer.server.port=3000"
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - ./backend:/usr/src/app
      - ./wait-for-it.sh:/wait-for-it.sh
    command: "npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pewpewlogs_frontend
    networks:
      - web
    ports:
      - "5173:5173" # Vite's default port
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.pewpewlogsfront_http.entrypoints=web"
      - "traefik.http.routers.pewpewlogsfront.service=pewpewlogs"
      - "traefik.http.routers.pewpewlogsfront_http.rule=Host(`${FQDN_PEWPEWLOGSFRONT}`)"
      - "traefik.http.routers.pewpewlogsfront_http.middlewares=redirect-web-to-websecure@internal"
      - "traefik.http.routers.pewpewlogsfront.rule=Host(`${FQDN_PEWPEWLOGSFRONT}`)"
      - "traefik.http.routers.pewpewlogsfront.entrypoints=websecure"
      - "traefik.http.routers.pewpewlogsfront.tls.certresolver=lets-encrypt"
      - "traefik.http.services.pewpewlogsfront.loadBalancer.server.port=5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    #command: "npm run dev"

networks:
  web:
    external: true

volumes:
  mariadb-data:
