version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - web

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pewpewlogs
    networks:
      - web
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.pewpewlogs_http.entrypoints=web"
      - "traefik.http.routers.pewpewlogs.service=pewpewlogs"
      - "traefik.http.routers.pewpewlogs_http.rule=Host(`${FQDN_PEWPEWLOGS}`)"
      - "traefik.http.routers.pewpewlogs_http.middlewares=redirect-web-to-websecure@internal"
      - "traefik.http.routers.pewpewlogs.rule=Host(`${FQDN_PEWPEWLOGS}`)"
      - "traefik.http.routers.pewpewlogs.entrypoints=websecure"
      - "traefik.http.routers.pewpewlogs.tls.certresolver=lets-encrypt"
      - "traefik.http.services.pewpewlogs.loadBalancer.server.port=3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      KINDE_DOMAIN: ${KINDE_DOMAIN}
      KINDE_CLIENT_ID: ${KINDE_CLIENT_ID}
      KINDE_CLIENT_SECRET: ${KINDE_CLIENT_SECRET}
      KINDE_REDIRECT_URI: ${KINDE_REDIRECT_URI}
      KINDE_LOGOUT_REDIRECT_URI: ${KINDE_LOGOUT_REDIRECT_URI}
      KINDE_POST_LOGIN_REDIRECT_URI: ${KINDE_POST_LOGIN_REDIRECT_URI}
    depends_on:
      - mariadb
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev

networks:
  web:
    external: true

volumes:
  mariadb-data:
