CREATE TABLE IF NOT EXISTS Weapons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  caliber VARCHAR(255) NOT NULL,
  toimintatapa VARCHAR(255) NOT NULL,
  erva BOOLEAN NOT NULL
);
